import { DocumentAnalysis, AnalysisStatus, IntelligenceInsight, HistoryDocument } from './types';


export const mockAnalysisResult: DocumentAnalysis = {
  id: 'analysis-001',
  documentId: 'doc-001',
  documentName: 'MSME Term Loan Agreement.pdf',
  lenderName: 'Apex Finance Pvt. Ltd.',
  analyzedAt: new Date(),

  overallRisk: {
    level: 'critical',
    score: 84,
    category: 'Predatory Lending',
    details:
      'This agreement contains multiple clauses that deviate significantly from RBI Fair Practices Code guidelines. The effective cost of borrowing is substantially higher than the stated rate, and several clauses create asymmetric obligations heavily favouring the lender.',
  },

  predatoryScore: 78,

  trueCost: {
    loanAmount: 2500000,
    tenure: 36,
    statedInterestRate: 18,
    effectiveAnnualRate: 31.4,
    processingFee: 75000,
    penalInterestRate: 36,
    prepaymentPenalty: 4,
    insurancePremium: 48000,
    otherCharges: 22000,
    totalRepayable: 3891000,
  },

  rbiViolations: [
    {
      id: 'rbi-001',
      regulation: 'RBI Fair Practices Code â€” Clause 3(a)',
      description:
        'Lender has not disclosed the annualised rate of interest in the sanction letter. Only a flat monthly rate is mentioned, obscuring the true cost.',
      severity: 'critical',
      clauseRef: 'Clause 4.1',
    },
    {
      id: 'rbi-002',
      regulation: 'RBI Master Circular â€” MSME Lending, Para 6',
      description:
        'Penal interest of 3% per month (36% p.a.) exceeds the permissible ceiling and is applied on the entire outstanding principal rather than the overdue amount.',
      severity: 'critical',
      clauseRef: 'Clause 7.3',
    },
    {
      id: 'rbi-003',
      regulation: 'RBI Fair Practices Code â€” Clause 5',
      description:
        'No grievance redressal mechanism or nodal officer details are mentioned in the agreement, violating mandatory disclosure requirements.',
      severity: 'high',
      clauseRef: 'General Terms',
    },
    {
      id: 'rbi-004',
      regulation: 'SARFAESI Act, 2002 â€” Section 13(2)',
      description:
        'The foreclosure notice period stated in the agreement (7 days) is shorter than the statutory minimum of 60 days.',
      severity: 'critical',
      clauseRef: 'Clause 11.2',
    },
  ],

  clauses: [
    {
      id: 'clause-001',
      title: 'Penal Interest on Default',
      clauseType: 'penal_charges',
      content:
        'In the event of default in payment of any instalment on the due date, the Borrower shall be liable to pay penal interest at the rate of 3% per month on the entire outstanding loan amount from the date of default until the date of actual payment, in addition to the regular interest.',
      riskLevel: 'critical',
      riskScore: 96,
      summary:
        '3% per month (36% p.a.) penal interest charged on the entire outstanding principal â€” not just the overdue amount. This is a classic predatory trap that can cause debt to spiral rapidly.',
      rbiViolation: 'Violates RBI Master Circular on MSME Lending â€” penal interest must apply only to the overdue amount and must be reasonable.',
      recommendations: [
        'Negotiate penal interest to apply only on the overdue instalment, not the full outstanding principal.',
        'Cap penal interest at 2% p.a. above the contracted rate, in line with RBI guidance.',
        'Insist on a 7-day cure period before penal interest kicks in.',
        'Request removal of compounding on penal interest.',
      ],
      lineNumber: 47,
    },
    {
      id: 'clause-002',
      title: 'Blanket Lien on Business Assets',
      clauseType: 'collateral',
      content:
        'As security for the Loan, the Borrower hereby grants to the Lender a first and exclusive charge over all present and future movable and immovable assets of the Borrower, including but not limited to machinery, inventory, receivables, intellectual property, and any other assets of whatsoever nature, whether or not specifically described herein.',
      riskLevel: 'critical',
      riskScore: 91,
      summary:
        'Unlimited blanket lien covers every asset the business owns or will ever own â€” including future assets not yet acquired. This gives the lender sweeping seizure rights far beyond the loan value.',
      recommendations: [
        'Limit collateral to specific, enumerated assets with agreed valuations.',
        'Exclude future assets from the charge â€” lien should only cover assets at the time of signing.',
        'Negotiate a release mechanism once the loan-to-collateral ratio falls below 1:1.',
        'Ensure intellectual property is explicitly excluded from the charge.',
      ],
      lineNumber: 63,
    },
    {
      id: 'clause-003',
      title: 'Unconditional Personal Guarantee',
      clauseType: 'guarantee',
      content:
        'The Guarantor(s) hereby unconditionally and irrevocably guarantee the due repayment of the Loan together with all interest, penal charges, costs, and expenses. The Lender may proceed against the Guarantor without first exhausting remedies against the Borrower or the collateral. The guarantee shall survive the death, insolvency, or dissolution of the Borrower.',
      riskLevel: 'critical',
      riskScore: 88,
      summary:
        'The lender can directly pursue the personal guarantor without first attempting recovery from the business or its assets. This puts the promoter\'s personal property at immediate risk.',
      recommendations: [
        'Negotiate a "see-first" clause requiring the lender to exhaust business assets before invoking the personal guarantee.',
        'Cap the personal guarantee at the loan principal only â€” exclude penal interest and charges.',
        'Add a sunset clause releasing the guarantee once 70% of the loan is repaid.',
        'Ensure the guarantee does not extend to future loans or facilities.',
      ],
      lineNumber: 82,
    },
    {
      id: 'clause-004',
      title: 'Foreclosure Notice Period â€” 7 Days',
      clauseType: 'foreclosure',
      content:
        'Upon occurrence of an Event of Default, the Lender shall be entitled to issue a demand notice to the Borrower. If the default is not cured within 7 (seven) days of such notice, the Lender may, without further notice, initiate recovery proceedings including seizure of collateral under applicable law.',
      riskLevel: 'critical',
      riskScore: 85,
      summary:
        'A 7-day foreclosure window is far below the 60-day statutory minimum under SARFAESI Act Section 13(2). This clause is legally unenforceable but signals aggressive lender intent.',
      rbiViolation: 'Directly violates SARFAESI Act, 2002 â€” Section 13(2) mandates a minimum 60-day notice period.',
      recommendations: [
        'This clause is void under SARFAESI Act â€” document this in writing before signing.',
        'Insist on explicit reference to the 60-day statutory notice period.',
        'Add a dispute resolution step before any foreclosure action can be initiated.',
        'Negotiate a 30-day cure period for first-time defaults.',
      ],
      lineNumber: 112,
    },
    {
      id: 'clause-005',
      title: 'Prepayment Penalty â€” 4% of Outstanding',
      clauseType: 'prepayment',
      content:
        'The Borrower may prepay the Loan in full or in part subject to payment of a prepayment premium of 4% (four percent) of the outstanding principal amount at the time of prepayment, plus applicable taxes. Partial prepayments shall not reduce the EMI amount but shall reduce the tenure.',
      riskLevel: 'high',
      riskScore: 74,
      summary:
        'A 4% prepayment penalty on the full outstanding balance is punitive and discourages the borrower from refinancing at better rates. RBI guidelines recommend zero or minimal prepayment charges for floating-rate MSME loans.',
      recommendations: [
        'For floating-rate loans, RBI guidelines prohibit prepayment penalties â€” verify the rate type.',
        'Negotiate the penalty down to 1â€“2% applicable only in the first 12 months.',
        'Ensure partial prepayments reduce EMI, not just tenure, to improve cash flow.',
        'Add a clause allowing penalty-free prepayment after 18 months.',
      ],
      lineNumber: 134,
    },
    {
      id: 'clause-006',
      title: 'Unilateral Interest Rate Revision',
      clauseType: 'interest_rate',
      content:
        'The Lender reserves the right to revise the rate of interest at any time during the tenure of the Loan at its sole discretion, with 30 days prior notice to the Borrower. The Borrower\'s continued repayment of instalments shall be deemed acceptance of the revised rate.',
      riskLevel: 'high',
      riskScore: 79,
      summary:
        'The lender can raise the interest rate at any time with just 30 days notice. Continued payment is treated as consent â€” the borrower has no meaningful right to object or exit without penalty.',
      rbiViolation: 'Violates RBI Fair Practices Code â€” interest rate changes must be linked to a benchmark and borrowers must have a genuine exit option.',
      recommendations: [
        'Insist on linking any rate revision to a published benchmark (e.g., RBI repo rate).',
        'Negotiate a cap on rate increases â€” no more than 2% above the original contracted rate.',
        'Add a clause allowing penalty-free exit within 60 days of any rate revision.',
        'Require written consent (not deemed consent) for any rate change.',
      ],
      lineNumber: 28,
    },
    {
      id: 'clause-007',
      title: 'One-Sided Arbitration Clause',
      clauseType: 'arbitration',
      content:
        'Any dispute arising out of or in connection with this Agreement shall be referred to a sole arbitrator appointed by the Lender. The arbitration shall be conducted in Mumbai. The costs of arbitration shall be borne entirely by the Borrower.',
      riskLevel: 'high',
      riskScore: 71,
      summary:
        'The lender appoints the arbitrator unilaterally and the borrower bears all costs. This effectively denies the MSME access to fair dispute resolution.',
      recommendations: [
        'Insist on a mutually agreed arbitrator or appointment by a neutral institution (e.g., ICADR).',
        'Negotiate for arbitration costs to be shared equally.',
        'Add an option for disputes below â‚¹10 lakh to be resolved through the Banking Ombudsman.',
        'Ensure the arbitration venue is the borrower\'s city of business.',
      ],
      lineNumber: 156,
    },
    {
      id: 'clause-008',
      title: 'Processing Fee â€” Non-Refundable',
      clauseType: 'disclosure',
      content:
        'The Borrower shall pay a non-refundable processing fee of 3% of the sanctioned loan amount at the time of disbursement. This fee is in addition to documentation charges, stamp duty, legal fees, and any other charges as may be levied by the Lender from time to time.',
      riskLevel: 'medium',
      riskScore: 58,
      summary:
        'A 3% processing fee on â‚¹25 lakh equals â‚¹75,000 upfront â€” effectively raising the cost of funds before the first EMI. The "from time to time" language allows additional undisclosed charges.',
      recommendations: [
        'Negotiate the processing fee down to 1â€“1.5%, which is market standard.',
        'Demand a complete, exhaustive list of all charges â€” reject open-ended "from time to time" language.',
        'Ensure all fees are disclosed in the Key Fact Statement (KFS) before signing.',
        'Request a partial refund of the processing fee if the loan is prepaid within 6 months.',
      ],
      lineNumber: 19,
    },
    {
      id: 'clause-009',
      title: 'Insurance Mandate â€” Lender-Specified Provider',
      clauseType: 'general',
      content:
        'The Borrower shall, as a condition of disbursement, obtain a credit life insurance policy from [Lender\'s affiliated insurer] covering the full loan amount. The premium shall be deducted from the disbursed amount. Failure to maintain the policy shall constitute an Event of Default.',
      riskLevel: 'medium',
      riskScore: 52,
      summary:
        'Mandatory insurance from the lender\'s own affiliate at a premium of â‚¹48,000 is deducted before disbursement, reducing the effective loan amount while the EMI is calculated on the full sanctioned amount.',
      recommendations: [
        'You have the right to choose your own insurer â€” this tied-selling practice may violate IRDA guidelines.',
        'Compare premiums from independent insurers; the affiliate premium is typically 30â€“50% higher.',
        'Negotiate for the insurance premium to be excluded from the EMI calculation base.',
        'Ensure the policy benefit goes to the business, not the lender.',
      ],
      lineNumber: 98,
    },
    {
      id: 'clause-010',
      title: 'Repayment Schedule â€” Fixed EMI, No Moratorium',
      clauseType: 'repayment',
      content:
        'The Borrower shall repay the Loan in 36 equal monthly instalments of â‚¹1,08,083 commencing from the date of disbursement. No moratorium period shall be applicable. The Lender shall not be obligated to restructure or reschedule the Loan under any circumstances.',
      riskLevel: 'low',
      riskScore: 32,
      summary:
        'No moratorium period means EMIs begin immediately from disbursement, before the business can deploy the capital. The "no restructuring" clause removes any flexibility during genuine hardship.',
      recommendations: [
        'Negotiate a 3-month moratorium on principal repayment to allow business deployment time.',
        'Add a force majeure clause allowing temporary EMI deferral during natural disasters or declared emergencies.',
        'Request a one-time restructuring option exercisable within the first 24 months.',
      ],
      lineNumber: 71,
    },
  ],

  keyFindings: [
    'Effective annual rate of 31.4% is 13.4 percentage points above the stated 18% â€” driven by hidden fees and charges.',
    'Penal interest of 36% p.a. on the entire outstanding principal violates RBI Master Circular on MSME Lending.',
    'Foreclosure notice period of 7 days is legally void â€” SARFAESI Act mandates a minimum of 60 days.',
    'Blanket lien on all present and future assets gives the lender disproportionate seizure rights.',
    'Personal guarantee is unconditional with no "see-first" requirement â€” promoter\'s personal assets are at immediate risk.',
    'Unilateral interest rate revision clause with deemed consent removes the borrower\'s right to object.',
    '4 out of 10 clauses directly violate RBI Fair Practices Code or SARFAESI Act provisions.',
  ],

  legalReferences: [
    'RBI Fair Practices Code for Lenders (Master Circular, 2015)',
    'SARFAESI Act, 2002 â€” Section 13(2): 60-day notice period',
    'RBI Master Circular â€” Credit Facilities to MSMEs',
    'MSME Development Act, 2006',
    'Arbitration and Conciliation Act, 1996 â€” Section 12 (Impartiality of Arbitrator)',
    'IRDA Guidelines on Tied Selling of Insurance Products',
  ],

  financialImpact: {
    estimatedCost: 1391000,
    confidence: 0.87,
    details:
      'You will pay â‚¹13.91 lakh more than the principal over the loan tenure. This includes â‚¹75,000 in processing fees, â‚¹48,000 in insurance premiums, â‚¹22,000 in other charges, and â‚¹12.46 lakh in interest â€” against a principal of â‚¹25 lakh.',
  },
};

export const mockProcessingStatuses: AnalysisStatus[] = [
  { phase: 'scanning',     progress: 15,  message: 'Scanning loan document structure and clauses',          estimatedTimeRemaining: 45 },
  { phase: 'extracting',   progress: 35,  message: 'Extracting interest rates, fees, and key terms',        estimatedTimeRemaining: 30 },
  { phase: 'analyzing',    progress: 65,  message: 'Checking clauses against RBI Fair Practices Code',      estimatedTimeRemaining: 15 },
  { phase: 'intelligence', progress: 85,  message: 'Calculating true cost and generating recommendations',  estimatedTimeRemaining: 5  },
  { phase: 'complete',     progress: 100, message: 'Analysis complete',                                     estimatedTimeRemaining: 0  },
];

export const mockIntelligenceInsights: IntelligenceInsight[] = [
  {
    category: 'risk',
    title: 'Debt Spiral Risk',
    description: 'Penal interest at 36% p.a. on the full outstanding principal can cause the debt to exceed the original loan amount within 4â€“5 months of default.',
    impact: 'high',
    actionable: true,
  },
  {
    category: 'compliance',
    title: '4 RBI Violations Detected',
    description: 'Clauses on penal interest, foreclosure notice, interest disclosure, and grievance redressal directly violate RBI Fair Practices Code and SARFAESI Act.',
    impact: 'high',
    actionable: true,
  },
  {
    category: 'risk',
    title: 'Personal Assets at Risk',
    description: 'The unconditional personal guarantee allows the lender to bypass business assets entirely and directly attach the promoter\'s personal property.',
    impact: 'high',
    actionable: true,
  },
  {
    category: 'optimization',
    title: 'True Cost is 31.4% p.a.',
    description: 'After accounting for processing fees, insurance, and other charges, the effective annual rate is 31.4% â€” not the 18% stated in the agreement.',
    impact: 'high',
    actionable: false,
  },
  {
    category: 'opportunity',
    title: 'Negotiate Before Signing',
    description: 'At least 6 of the 10 flagged clauses are negotiable. Lenders routinely accept modifications to penal interest, prepayment penalty, and guarantee terms.',
    impact: 'medium',
    actionable: true,
  },
];

export const getProcessingStatus = (
  phase: 'scanning' | 'extracting' | 'analyzing' | 'intelligence' | 'complete'
): AnalysisStatus => {
  return mockProcessingStatuses.find((s) => s.phase === phase) || mockProcessingStatuses[0];
};

export const mockHistoryDocuments: HistoryDocument[] = [
  {
    id: 'h-001',
    name: 'MSME Term Loan Agreement.pdf',
    lenderName: 'Apex Finance Pvt. Ltd.',
    analyzedAt: new Date('2024-11-10'),
    riskLevel: 'critical',
    riskScore: 84,
    predatoryScore: 78,
    size: '1.4 MB',
    clauseBreakdown: { critical: 4, high: 3, medium: 2, low: 1 },
    rbiViolations: 4,
    statedRate: 18,
    effectiveRate: 31.4,
    loanAmount: 2500000,
    tenure: 36,
    totalRepayable: 3891000,
    demographics: {
      businessName: 'Ravi Textiles & Co.',
      sector: 'Manufacturing â€” Textiles',
      yearsInOperation: 6,
      annualTurnover: 'â‚¹1.2 Cr',
      state: 'Tamil Nadu',
      borrowerType: 'Small',
      loanPurpose: 'Working capital & machinery upgrade',
      firstTimeBorrower: false,
    },
    keyFlags: [
      '36% p.a. penal interest on full outstanding principal',
      'Blanket lien on all present and future assets',
      'Unconditional personal guarantee â€” no see-first clause',
      '7-day foreclosure notice (SARFAESI minimum is 60 days)',
    ],
    analysis: mockAnalysisResult,
  },
  {
    id: 'h-002',
    name: 'Business Loan Sanction Letter.pdf',
    lenderName: 'QuickCredit NBFC Ltd.',
    analyzedAt: new Date('2024-11-06'),
    riskLevel: 'high',
    riskScore: 71,
    predatoryScore: 63,
    size: '980 KB',
    clauseBreakdown: { critical: 2, high: 4, medium: 3, low: 2 },
    rbiViolations: 2,
    statedRate: 22,
    effectiveRate: 28.7,
    loanAmount: 1500000,
    tenure: 24,
    totalRepayable: 2184000,
    demographics: {
      businessName: 'Priya Food Processing',
      sector: 'Food & Beverage Processing',
      yearsInOperation: 3,
      annualTurnover: 'â‚¹68 L',
      state: 'Maharashtra',
      borrowerType: 'Micro',
      loanPurpose: 'Purchase of cold storage equipment',
      firstTimeBorrower: true,
    },
    keyFlags: [
      'Flat interest rate quoted â€” actual reducing-balance rate is 28.7%',
      'Prepayment penalty of 5% applicable throughout tenure',
      'Lender can recall loan with 15-day notice for any reason',
      'No grievance redressal officer named â€” RBI violation',
    ],
    analysis: {
      ...mockAnalysisResult,
      id: 'analysis-002',
      documentName: 'Business Loan Sanction Letter.pdf',
      lenderName: 'QuickCredit NBFC Ltd.',
      predatoryScore: 63,
      overallRisk: {
        level: 'high',
        score: 71,
        category: 'Predatory Lending',
        details: 'Flat rate misrepresentation and aggressive recall clause are the primary concerns.',
      },
      trueCost: {
        loanAmount: 1500000,
        tenure: 24,
        statedInterestRate: 22,
        effectiveAnnualRate: 28.7,
        processingFee: 45000,
        penalInterestRate: 30,
        prepaymentPenalty: 5,
        insurancePremium: 28000,
        otherCharges: 11000,
        totalRepayable: 2184000,
      },
      rbiViolations: [
        {
          id: 'rbi-a',
          regulation: 'RBI Fair Practices Code â€” Clause 3(a)',
          description: 'Interest rate quoted as flat rate without disclosing the equivalent reducing-balance rate, obscuring the true cost of borrowing.',
          severity: 'critical',
          clauseRef: 'Clause 3.1',
        },
        {
          id: 'rbi-b',
          regulation: 'RBI Fair Practices Code â€” Clause 5',
          description: 'No grievance redressal mechanism or nodal officer contact details provided in the sanction letter.',
          severity: 'high',
          clauseRef: 'General Terms',
        },
      ],
    },
  },
  {
    id: 'h-003',
    name: 'Mudra Loan Agreement â€” Kishore.pdf',
    lenderName: 'State Bank of India',
    analyzedAt: new Date('2024-10-29'),
    riskLevel: 'low',
    riskScore: 24,
    predatoryScore: 18,
    size: '760 KB',
    clauseBreakdown: { critical: 0, high: 1, medium: 2, low: 5 },
    rbiViolations: 0,
    statedRate: 10.5,
    effectiveRate: 11.8,
    loanAmount: 500000,
    tenure: 60,
    totalRepayable: 641000,
    demographics: {
      businessName: 'Suresh Auto Garage',
      sector: 'Automotive Services & Repair',
      yearsInOperation: 9,
      annualTurnover: 'â‚¹32 L',
      state: 'Karnataka',
      borrowerType: 'Micro',
      loanPurpose: 'Expansion of service bay and tool purchase',
      firstTimeBorrower: false,
    },
    keyFlags: [
      'Minor: Processing fee slightly above MUDRA scheme guidelines',
      'Insurance mandate present but borrower can choose own insurer',
    ],
    analysis: {
      ...mockAnalysisResult,
      id: 'analysis-003',
      documentName: 'Mudra Loan Agreement â€” Kishore.pdf',
      lenderName: 'State Bank of India',
      predatoryScore: 18,
      overallRisk: {
        level: 'low',
        score: 24,
        category: 'Standard Lending',
        details: 'Agreement broadly compliant with RBI guidelines. Minor concerns around processing fee disclosure.',
      },
      trueCost: {
        loanAmount: 500000,
        tenure: 60,
        statedInterestRate: 10.5,
        effectiveAnnualRate: 11.8,
        processingFee: 7500,
        penalInterestRate: 12,
        prepaymentPenalty: 0,
        insurancePremium: 9000,
        otherCharges: 2500,
        totalRepayable: 641000,
      },
      rbiViolations: [],
    },
  },
  {
    id: 'h-004',
    name: 'Equipment Finance Agreement.pdf',
    lenderName: 'Bajaj Finserv Ltd.',
    analyzedAt: new Date('2024-10-18'),
    riskLevel: 'high',
    riskScore: 68,
    predatoryScore: 59,
    size: '1.1 MB',
    clauseBreakdown: { critical: 1, high: 5, medium: 3, low: 1 },
    rbiViolations: 1,
    statedRate: 16,
    effectiveRate: 23.1,
    loanAmount: 3500000,
    tenure: 48,
    totalRepayable: 5460000,
    demographics: {
      businessName: 'Mehta Engineering Works',
      sector: 'Metal Fabrication & Engineering',
      yearsInOperation: 14,
      annualTurnover: 'â‚¹4.8 Cr',
      state: 'Gujarat',
      borrowerType: 'Small',
      loanPurpose: 'CNC machine purchase',
      firstTimeBorrower: false,
    },
    keyFlags: [
      'Residual value clause allows lender to revalue collateral annually',
      'Cross-default clause links this loan to all other lender facilities',
      'Mandatory insurance from lender-affiliated provider at 2.1x market rate',
      'Arbitration venue fixed at lender\'s city (Mumbai) â€” borrower is in Ahmedabad',
    ],
    analysis: {
      ...mockAnalysisResult,
      id: 'analysis-004',
      documentName: 'Equipment Finance Agreement.pdf',
      lenderName: 'Bajaj Finserv Ltd.',
      predatoryScore: 59,
      overallRisk: {
        level: 'high',
        score: 68,
        category: 'Aggressive Lending',
        details: 'Cross-default and annual revaluation clauses create significant ongoing risk for the borrower.',
      },
      trueCost: {
        loanAmount: 3500000,
        tenure: 48,
        statedInterestRate: 16,
        effectiveAnnualRate: 23.1,
        processingFee: 105000,
        penalInterestRate: 28,
        prepaymentPenalty: 3,
        insurancePremium: 84000,
        otherCharges: 31000,
        totalRepayable: 5460000,
      },
      rbiViolations: [
        {
          id: 'rbi-c',
          regulation: 'IRDA Guidelines â€” Tied Selling',
          description: 'Borrower is mandated to purchase insurance from the lender\'s affiliated insurer with no option to choose an independent provider.',
          severity: 'high',
          clauseRef: 'Clause 9.4',
        },
      ],
    },
  },
  {
    id: 'h-005',
    name: 'Working Capital CC Limit Agreement.pdf',
    lenderName: 'HDFC Bank Ltd.',
    analyzedAt: new Date('2024-10-05'),
    riskLevel: 'medium',
    riskScore: 47,
    predatoryScore: 38,
    size: '890 KB',
    clauseBreakdown: { critical: 0, high: 2, medium: 5, low: 4 },
    rbiViolations: 0,
    statedRate: 14.5,
    effectiveRate: 17.2,
    loanAmount: 2000000,
    tenure: 12,
    totalRepayable: 2344000,
    demographics: {
      businessName: 'Kapoor Pharma Distributors',
      sector: 'Pharmaceutical Distribution',
      yearsInOperation: 11,
      annualTurnover: 'â‚¹9.2 Cr',
      state: 'Delhi',
      borrowerType: 'Small',
      loanPurpose: 'Working capital â€” inventory financing',
      firstTimeBorrower: false,
    },
    keyFlags: [
      'Annual review clause allows bank to reduce limit without notice',
      'Hypothecation covers all present and future stock-in-trade',
    ],
    analysis: {
      ...mockAnalysisResult,
      id: 'analysis-005',
      documentName: 'Working Capital CC Limit Agreement.pdf',
      lenderName: 'HDFC Bank Ltd.',
      predatoryScore: 38,
      overallRisk: {
        level: 'medium',
        score: 47,
        category: 'Standard with Concerns',
        details: 'Broadly fair agreement from a regulated bank. Annual review and hypothecation scope are the main areas to negotiate.',
      },
      trueCost: {
        loanAmount: 2000000,
        tenure: 12,
        statedInterestRate: 14.5,
        effectiveAnnualRate: 17.2,
        processingFee: 40000,
        penalInterestRate: 18,
        prepaymentPenalty: 0,
        insurancePremium: 0,
        otherCharges: 14000,
        totalRepayable: 2344000,
      },
      rbiViolations: [],
    },
  },
];

